# Generated by Django 2.1.4 on 2019-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniFestAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
